"""add variant id to order items

Revision ID: b6d7b96c6d17
Revises: 5fe510d5d45e
Create Date: 2026-08-19 08:52:12.619584+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6d7b96c6d17'
down_revision: Union[str, None] = '5fe510d5d45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'variant_id')
    # ### end Alembic commands ###
