"""initial schema

Revision ID: 482750d08d54
Revises:
Create Date: 2026-08-18 23:42:51.675991+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '482750d08d54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.ARRAY(sa.Integer()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_level', 'categories', ['level'], unique=False)
    op.create_index('idx_category_parent', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_category_path', 'categories', ['path'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='client', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_date', sa.DateTime(), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=False),
    sa.Column('gdpr_consent_date', sa.DateTime(), nullable=True),
    sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_accepted_date', sa.DateTime(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent_date', sa.DateTime(), nullable=True),
    sa.Column('data_deletion_requested', sa.Boolean(), nullable=False),
    sa.Column('data_deletion_date', sa.DateTime(), nullable=True),
    sa.Column('data_retention_period', sa.Integer(), nullable=False),
    sa.Column('consent_history', sa.JSON(), nullable=False),
    sa.Column('data_export_requests', sa.JSON(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('client', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activity', 'users', ['last_login', 'last_activity_date', 'is_active'], unique=False)
    op.create_index('idx_user_email_verified', 'users', ['is_email_verified'], unique=False)
    op.create_index('idx_user_gdpr', 'users', ['gdpr_consent', 'privacy_policy_accepted', 'data_deletion_requested'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('address_type', sa.String(), server_default='home', nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('delivery_phone', sa.String(), nullable=True),
    sa.Column('delivery_instructions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("address_type IN ('home', 'work', 'other')", name='ck_address_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_active', 'addresses', ['is_active'], unique=False)
    op.create_index('idx_address_default', 'addresses', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_address_user', 'addresses', ['user_id'], unique=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index('uix_active_user_address', 'addresses', ['user_id', 'street', 'city', 'state', 'postal_code', 'country', 'is_active'], unique=True, postgresql_where='is_active')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('characteristics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_product_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_product_name_description', 'products', ['name', 'description'], unique=False)
    op.create_index('idx_product_price', 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('payment_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_address_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending', 'paid', 'failed', 'refunded')", name='ck_payment_status'),
    sa.CheckConstraint("status IN ('new', 'confirmed', 'processing', 'sent', 'delivered', 'cancelled')", name='ck_order_status'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_index('idx_order_user_id', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index('uix_order_user_idempotency_key', 'orders', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('payment_intent_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_refunded', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'idempotency_key', name='uix_payment_order_idempotency_key')
    )
    op.create_index('idx_payment_order_id', 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_intent_id'), 'payments', ['payment_intent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('idx_payment_order_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('uix_order_user_idempotency_key', table_name='orders', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_order_user_id', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('idx_product_price', table_name='products')
    op.drop_index('idx_product_name_description', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_index('idx_product_active', table_name='products')
    op.drop_table('products')
    op.drop_index('uix_active_user_address', table_name='addresses', postgresql_where='is_active')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index('idx_address_user', table_name='addresses')
    op.drop_index('idx_address_default', table_name='addresses')
    op.drop_index('idx_address_active', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_gdpr', table_name='users')
    op.drop_index('idx_user_email_verified', table_name='users')
    op.drop_index('idx_user_activity', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_category_path', table_name='categories')
    op.drop_index('idx_category_parent', table_name='categories')
    op.drop_index('idx_category_level', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
