"""add checkout session columns to payments

Revision ID: ed98c07e2fbc
Revises: b6d7b96c6d17
Create Date: 2026-08-19 12:00:00.000000+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed98c07e2fbc'
down_revision: Union[str, None] = 'b6d7b96c6d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_session_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('checkout_session_url', sa.String(), nullable=True))
    op.create_index(
        op.f('ix_payments_checkout_session_id'), 'payments', ['checkout_session_id'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_checkout_session_id'), table_name='payments')
    op.drop_column('payments', 'checkout_session_url')
    op.drop_column('payments', 'checkout_session_id')
    # ### end Alembic commands ###
